### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by mbautista** [joone/loz#12]
Hello,
This is a great program, thank you very much :)

I've installed with npm on ubuntu 20.04, it works great without arguments (chat mode), but I have no output when I add an argument : 
```
$ loz
Loz: a simple ChatGTP CLI tool
  mode: default
> bonjour, comment allez-vous ?
Bonjour ! Je suis une intelligence artificielle, donc je n'ai pas de sentiments, mais je suis prêt à vous aider. Comment puis-je vous assister aujourd'hui ?
> quit
Good bye!

$ loz "bonjour"
(nothing...)
^C

$ loz "quelle est la racine carrée de 9 ?"
(nothing...)
^C
```
Could anyone help me please ?
Thank you very much :)
Mathieu.

**Comment by joone** [comment]
Thanks for filing a bug. I will take a look at the issue.

**Comment by joone** [comment]
can you try the new release(0.1.10)?

**Comment by joone** [comment]
This bug has been resolved. Please let me know if the issue reoccurs.
