### ISSUE TITLE
LOZ always requires `OPENAI_API_KEY` even if want to use `ollama`.

### ISSUE THREAD

**Issue by 134130** [joone/loz#13]
- I'm running loz on macos.
- installed nodejs with `n` which is nodejs version manager.
- `n` is installed with homebrew.
- With `npm -g` install, `which loz` -> `/opt/homebrew/bin/loz`
- After then, any commands requires `OPENAI_API_KEY`. (even initial configuring message is not appears)
- I just want to use `loz` with my local `ollama`.

**Comment by joone** [comment]
You can set the OPEN_API_KEY with a dummy value and then try running loz. I will be checking this issue on a Mac.

**Comment by 134130** [comment]
yes. I've configured ollama with dummy envvar.
But even then, loz requires OPENAPI key, and if dummy given, It tries with dummy key and returns 500.

**Comment by joone** [comment]
can you update config.json like this?

```
vi ~/.loz/config.json
```

```
{
  "items": [
    {
      "name": "mode",
      "value": "default"
    },
    {
      "name": "api",
      "value": "ollama"
    }
  ]
}
```

**Comment by joone** [comment]
You can try the latest update now. :-)
