### ISSUE TITLE
Error: Failed with status code: 500 with ollama

### ISSUE THREAD

**Issue by hoonyyhoon** [joone/loz#14]
Hi! Thank you for sharing wonderful project.

I've just tried ollama setup and encountered error when using with git(e.g. `git diff HEAD~1 | loz -g`)

seems like `/api/generate` to ollama is throwing 500

below is some part of the api log with `ollama serve` when calling git
```
[GIN] 2024/02/01 - 07:51:11 | 200 |      185.75µs |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/02/01 - 07:51:11 | 200 |     192.625µs |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/02/01 - 07:51:11 | 200 |     194.417µs |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/02/01 - 07:51:11 | 200 |     533.875µs |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/02/01 - 07:51:11 | 200 |      322.25µs |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/02/01 - 07:51:11 | 200 |      337.75µs |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/02/01 - 07:51:11 | 200 |      962.75µs |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/02/01 - 07:51:11 | 500 |     777.416µs |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/02/01 - 07:51:11 | 500 |     181.875µs |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/02/01 - 07:51:11 | 500 |     190.625µs |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/02/01 - 07:51:11 | 500 |     350.666µs |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/02/01 - 07:51:11 | 500 |      591.25µs |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/02/01 - 07:51:11 | 500 |     194.333µs |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/02/01 - 07:51:11 | 500 |     381.417µs |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/02/01 - 07:51:11 | 500 |     583.583µs |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/02/01 - 07:51:11 | 500 |    1.196083ms |       127.0.0.1 | POST     "/api/generate"
```

but, when I send the promt by api call it returns response with 200

```
curl -X POST http://localhost:11434/api/generate \
-H "Content-Type: application/json" \
-d "{
  \"model\": \"llama2\",
  \"prompt\": \"diff --git with {git diff message}\"
}"

```

For some more information to fix this,
- M1 Pro, loz with 0.2.7, ollama with 0.1.22
- also, one thing to note is interactive shell(`loz`) works well

I'll try keep posting when I try further to debug this. Any suggestions or guess on resolving these HTTP 500 errors would be greatly helpful, Thank you again!

**Comment by hoonyyhoon** [comment]
Below is what I got from `this.api.generate`(https://github.com/joone/loz/blob/b14386e387579b35d146697c01a2c6d56188cbc3/src/llm/index.ts#L87)

`There was a problem generating output from codellama with the prompt`

When I change the model to `llama2` it works.(https://github.com/joone/loz/blob/b14386e387579b35d146697c01a2c6d56188cbc3/src/index.ts#L248)

Guess there are some difference when using codellama, let me know if same thing happens in other env as well.
I'll look into ollama code further later.

**Comment by joone** [comment]
You can change the model by entering:

> config model llama2

or

> config model codelamma
