### ISSUE TITLE
error ubuntu in windows 10

### ISSUE THREAD

**Issue by UltraSteph06** [joone/loz#3]
hi
I have OPENAI_API_KEY in ./bashrc configured.
But when i launch loz, i have this error :
An error occurred during OpenAI request:  TypeError: Cannot read property 'data' of undefined
    at Loz.<anonymous> (/usr/local/lib/node_modules/loz/dist/index.js:224:21)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/loz/dist/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Have you any idea ?

**Comment by valentingol** [comment]
Same issue on Ubuntu 22.04

**Comment by joone** [comment]
okay, I will check it

**Comment by joone** [comment]
When I tried to install the "loz" package using the npm install command on an Ubuntu 20.04 shell with WSL2, it didn't work for me. 
However, I was able to resolve the issue by creating a symbolic link as follows:
```
sudo ln -s /usr/local/node_modules/loz/bin/index.js loz
```

Then, it started working properly. Can you re-install the latest one and try to run it?

**Comment by joone** [comment]
You can now use ollama instead of OpenAI API.
