### ISSUE TITLE
Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by jmfergeau** [joone/loz#4]
As title says. Tested on a fresh arch linux, installed via npm in global. Appears whenever i send a prompt to the ai.
Complete log:
```
An error occurred during OpenAI request:  TypeError: Cannot read properties of undefined (reading 'data')
    at Loz.<anonymous> (/usr/lib/node_modules/loz/dist/index.js:224:21)
    at Generator.throw (<anonymous>)
    at rejected (/usr/lib/node_modules/loz/dist/index.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Yes, i've included the api key. it's even visible in the json logs. I avoided including them here for privacy purposes.
thanks

**Comment by Djibdjib** [comment]
Same here ...

**Comment by dbocart** [comment]
> I installed the git clone version and everything is ok !

Git clone installation is fail for me :/

**Comment by jmfergeau** [comment]
Installed via git clone and it... kinda worked since the error disappeared to leave a `Request failed with status code 429: API request limit reached` while it's the first time in 3 days i used the API!

I don't understand why it didn't worked with npm thought since the **install.sh actually uses npm** to install it!

Also, dev, fyi, not everyone is on debian. Don't expect apt to work on arch or fedora :D

**Comment by Dushime121** [comment]
> As title says. Tested on a fresh arch linux, installed via npm in global. Appears whenever i send a prompt to the ai. Complete log:
> 
> ```
> An error occurred during OpenAI request:  TypeError: Cannot read properties of undefined (reading 'data')
>     at Loz.<anonymous> (/usr/lib/node_modules/loz/dist/index.js:224:21)
>     at Generator.throw (<anonymous>)
>     at rejected (/usr/lib/node_modules/loz/dist/index.js:6:65)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```
> 
> Yes, i've included the api key. it's even visible in the json logs. I avoided including them here for privacy purposes. thanks

**Comment by Dushime121** [comment]
Same problem

**Comment by joone** [comment]
Regarding the error: 429: API request limit reached, you need to set up a payment method in order to continue using the API because you have exceeded your free quote.
https://platform.openai.com/account/billing/payment-methods

**Comment by jmfergeau** [comment]
> @jmfergeau Regarding the error: 429: API request limit reached, you need to set up a payment method in order to continue using the API because you have exceeded your free quote. https://platform.openai.com/account/billing/payment-methods

yeah, this I got it. (still doesn't explain how i could exceed my quota by doing nothing for days)
And still having the first error if i use the version provided in npm repos. i guess sending them an update? (I'm not sure how npm works for sending package updates)

**Comment by joone** [comment]
Please try the recent update. Thanks!
