### ISSUE TITLE
Request failed with status code 429: API request limit reached

### ISSUE THREAD

**Issue by IssouLinux** [joone/loz#6]
I tried with several API keys from different accounts, which I am certain they didn't reached the request limit (I can use the browser version of chatgpt) but I always get this error:
Luv: a simple ChatGTP CLI tool
  mode: default
> hi
Request failed with status code 429:
API request limit reached

**Comment by nazrvn** [comment]
same problem here

**Comment by joone** [comment]
I'm fixing it now.

**Comment by joone** [comment]
Since you have exceeded your free quote, it is necessary to set up a payment method in order to continue using the API. 
https://platform.openai.com/account/billing/payment-methods

I had the same issue. After setting up a payment, the API started working.
